language: python
python:
  - 2.7
services:
  - postgresql
env:
  - FLASK_APP=backend/app.py
  - FLASK_DEBUG=1
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install pylint
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - pycodestyle backend
  - pylint backend